### PR TITLE
Brave Otel Encoder implementation (continuation of #4)

### PR DESCRIPTION
**Pull request by making**
Addressed the review comments in #4.

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
@making I think trying to salvage #4 is a a cure worse than the disease. Can you set the target branch to main and just limit this to the encoder implementation? If you have a tidy (like license header change which is on main), go ahead and raise that and lets merge that quick to reduce the scope of this.

**Comment by codefromthecrypt** [comment]
also, let's make this a single commit as basically if this were someone else, they would just make a new PR as that's easier, and that would be 1 commit. Dozens of commits explains #4 maybe, but that isn't the goal of the work. The goal is to make an encoder and imho the prior impl makes that harder to understand than starting fresh.

**Comment by making** [comment]
Ok, I will do that

**Comment by making** [comment]
superceded by #9

**Pull request closed without merging**
